[package]
name = "poker_activity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
schnorrkel = "0.11.4"
sha2 = "0.10"
merlin = "3.0.0"
rand_core = "0.6.4"